os: linux
services:
    - docker
sudo: required
language: python
env:
    global:
        - CONAN_REFERENCE: "statsdclient/0.0.2"
        - CONAN_USERNAME: "vthiery"
        - CONAN_CHANNEL: "stable"
        - CONAN_UPLOAD: "https://api.bintray.com/conan/vthiery/conan-packages"

    matrix:
        - CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63

install:
    - ./.travis/install.sh
script:
    - ./.travis/run.sh